from pathlib import Path
from typing import Any

USER_CONFIG_PATH: Path
PROJECT_CONFIG_NAME: str

def config_path() -> Path: ...
def project_config_path(cwd: str | Path | None = None) -> Path: ...
def load_config(
    path: str | Path | None = None,
    *,
    include_project: bool = True,
    cwd: str | Path | None = None,
) -> dict[str, str | None]: ...
def save_config(path: str | Path | None = None) -> Path: ...
def get_config(key: str | None = None) -> Any: ...
def set_config(key: str, value: str | Path | None, *, save: bool = False) -> None: ...
def reset_config(*, save: bool = False) -> dict[str, str | None]: ...
