message(STATUS "Load Parallel Backend Options from ${PARALLEL_FILE}")

include("${PROJECT_ROOT_DIR}/cmake/utils/checkBackend.cmake")

set(PARALLEL
    "auto"
    CACHE STRING "parallel backend for SPONGE")
message(STATUS "-- Parallel backend input: ${PARALLEL}")

if(NOT DEFINED ON_ARM)
  string(TOLOWER "${CMAKE_SYSTEM_PROCESSOR}" SYSTEM_PROCESSOR_LOWER)
  if(SYSTEM_PROCESSOR_LOWER MATCHES "^(aarch64|arm64|arm)")
    set(ON_ARM TRUE)
  else()
    set(ON_ARM FALSE)
  endif()
endif()
message(STATUS "-- ON_ARM: ${ON_ARM} (processor: ${CMAKE_SYSTEM_PROCESSOR})")

searchoptions("${PROJECT_ROOT_DIR}/cmake/parallel/*.cmake" PARALLEL_OPTIONS)

set(PARALLEL_BACKEND)
if(PARALLEL STREQUAL "auto")
  message(STATUS "-- Auto detecting parallel backend")
  foreach(CHECK_FUNCTION ${PARALLEL_BACKEND_GPU_CHECK_FUNCTIONS})
    if(NOT PARALLEL_BACKEND)
      cmake_language(CALL ${CHECK_FUNCTION})
    endif()
  endforeach()
  foreach(CHECK_FUNCTION ${PARALLEL_BACKEND_CPU_CHECK_FUNCTIONS})
    if(NOT PARALLEL_BACKEND)
      cmake_language(CALL ${CHECK_FUNCTION})
    endif()
  endforeach()
  if(NOT PARALLEL_BACKEND)
    set(PARALLEL_BACKEND "none")
  endif()
elseif(PARALLEL STREQUAL "gpu")
  message(STATUS "-- Auto detecting parallel backend")
  foreach(CHECK_FUNCTION ${PARALLEL_BACKEND_GPU_CHECK_FUNCTIONS})
    if(NOT PARALLEL_BACKEND)
      cmake_language(CALL ${CHECK_FUNCTION})
    endif()
  endforeach()
  if(NOT PARALLEL_BACKEND)
    message(FATAL_ERROR "Unrecognized parallel backend option: ${PARALLEL}")
  endif()
elseif(PARALLEL STREQUAL "cpu")
  message(STATUS "-- Auto detecting parallel backend")
  foreach(CHECK_FUNCTION ${PARALLEL_BACKEND_CPU_CHECK_FUNCTIONS})
    if(NOT PARALLEL_BACKEND)
      cmake_language(CALL ${CHECK_FUNCTION})
    endif()
  endforeach()
  if(NOT PARALLEL_BACKEND)
    set(PARALLEL_BACKEND "none")
  endif()
elseif(PARALLEL IN_LIST PARALLEL_OPTIONS)
  set(PARALLEL_BACKEND ${PARALLEL})
else()
  message(FATAL_ERROR "Unrecognized parallel backend option: ${PARALLEL}")
endif()

set(PARALLEL_BACKEND_FILE
    "${PROJECT_ROOT_DIR}/cmake/parallel/${PARALLEL_BACKEND}.cmake")
include(${PARALLEL_BACKEND_FILE})
message(STATUS "Load parallel backend settings from ${PARALLEL_BACKEND_FILE}")

message(STATUS "-- Parallel backend: ${PARALLEL_BACKEND}")
list(APPEND PARALLEL_OPTIONS "cpu")
list(APPEND PARALLEL_OPTIONS "gpu")
list(APPEND PARALLEL_OPTIONS "auto")
message(
  STATUS "------------------------------------------------------------------")
